/**
 * 30-second song previews (official Apple/iTunes preview clips), keyed by
 * `"<artist>|<song title>"` — exactly as they appear in `albums.ts`.
 *
 * GENERATED by scripts/fetch-previews (iTunes Search API lookup); safe to
 * regenerate. Apple preview URLs are stable in practice but not guaranteed
 * forever — if one 404s, re-run the lookup for that track.
 */
export const SONG_PREVIEWS: Record<string, string> = {
  "ABBA|Angeleyes":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/d1/a5/64/d1a56444-903f-6c93-ebb0-9d018fdbd622/mzaf_6545965013322906786.plus.aac.p.m4a",
  "ABBA|Dancing Queen":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1a/47/93/1a4793fc-1586-87bc-00d2-dc4916a61c7c/mzaf_13920610926910283055.plus.aac.p.m4a",
  "ABBA|The Winner Takes It All":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fd/6d/12/fd6d123d-e356-cd43-b036-2ae2218bca1e/mzaf_2532642148093309877.plus.aac.p.m4a",
  "Billy Joel|Just the Way You Are":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/da/a8/77/daa877a9-ea6a-5026-1462-708b22ad1419/mzaf_9295306610003421988.plus.aac.p.m4a",
  "Billy Joel|She's Always a Woman":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/a4/6b/6c/a46b6cd0-b284-ecb8-020f-02bf22431152/mzaf_8360663882256182392.plus.aac.p.m4a",
  "Billy Joel|Vienna":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e8/d2/03/e8d203cc-ce97-278b-5abb-c6de33d36d37/mzaf_5153648922176185845.plus.aac.p.m4a",
  "Bruno Mars|Locked Out of Heaven":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f4/37/44/f4374481-e6e8-54d1-32ad-893ec2f4d495/mzaf_3915415747653767603.plus.aac.p.m4a",
  "Bruno Mars|Treasure":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/c9/74/29/c9742925-5c00-3529-9d23-488c9cb943b4/mzaf_7699598865223801718.plus.aac.p.m4a",
  "Bruno Mars|When I Was Your Man":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/82/d2/9a/82d29a5f-d9a0-57f4-c0ec-f785969240c3/mzaf_5320660780349800682.plus.aac.p.m4a",
  "Daniel Caesar|Best Part":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/cc/95/ed/cc95edc8-4f9b-0c56-bc74-31ba76a057f9/mzaf_11346187551197903108.plus.aac.p.m4a",
  "Daniel Caesar|Hold Me Down":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/9e/cf/00/9ecf002c-7da7-a3a6-354a-2ca47bc845d6/mzaf_16209809978753616855.plus.aac.p.m4a",
  "Daniel Caesar|Loose":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/3b/6c/9a/3b6c9a8d-ad67-e10e-f205-8a6c4048f250/mzaf_14579683229233280679.plus.aac.p.m4a",
  "Drake|2 Hard 4 The Radio":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fd/7f/fa/fd7ffaf1-1790-1b8d-9ba2-840b1d001fac/mzaf_9744536527102695989.plus.aac.p.m4a",
  "Drake|Feel No Ways":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/8a/69/7a/8a697ad6-ea57-ff2e-0615-836064f817fc/mzaf_6128837073092275498.plus.aac.p.m4a",
  "Drake|Keep the Family Close":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/6d/3a/c7/6d3ac7ef-06d4-3143-febc-2b7f18787988/mzaf_8692416335074936063.plus.aac.p.m4a",
  "Drake|National Treasures":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/16/04/63/160463ef-20fb-2e17-3b7b-1d916ea40fd2/mzaf_3195755801559110536.plus.aac.p.m4a",
  "Drake|One Dance":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/a8/bd/68/a8bd68a2-dcd2-9024-3859-3a9fd6d53576/mzaf_16864609147187531487.plus.aac.p.m4a",
  "Drake|Over My Dead Body":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/ba/6f/6b/ba6f6b02-d3cb-0691-d661-6ada537336ce/mzaf_16338940989983080305.plus.aac.p.m4a",
  "Drake|Shot for Me":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f4/4f/ac/f44facfb-73e7-4821-b577-4a18d522fd82/mzaf_2218691093128924958.plus.aac.p.m4a",
  "Drake|Slime You Out":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/7a/31/4d/7a314d17-abf6-d322-e04c-f04aa9f13a9c/mzaf_8166785415651777298.plus.aac.p.m4a",
  "Drake|Take Care":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/41/ad/df/41addf10-dff4-06f6-9109-fd24959cba0f/mzaf_3571059677903912007.plus.aac.p.m4a",
  "Drake|Tried Our Best":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/da/1b/13/da1b134b-455e-08a9-9757-340ff15b79c4/mzaf_9301648765748478625.plus.aac.p.m4a",
  "Drake|Virginia Beach":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/4b/88/3e/4b883ebd-6ed6-1dbd-76f7-78950c781c6b/mzaf_14888895774834105828.plus.aac.p.m4a",
  "Drake|Whisper My Name":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/bf/b9/19/bfb919e7-71ce-7dcc-5153-f1d0a55393c7/mzaf_12434464070158687599.plus.aac.p.m4a",
  "Fleetwood Mac|Dreams":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/d4/37/e7/d437e72a-c41b-332c-f196-bee295a9d673/mzaf_11574904347171701919.plus.aac.p.m4a",
  "Fleetwood Mac|Landslide":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/c3/ef/3a/c3ef3af9-c1bd-6c59-8c43-b5ca5398b928/mzaf_7314623142360207399.plus.aac.p.m4a",
  "Fleetwood Mac|Silver Springs":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/12/ac/1f/12ac1f8a-a3ca-8e49-4d5a-b0e5460938f3/mzaf_6633595999647848631.plus.aac.p.m4a",
  "Frank Ocean|Nights":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/9a/68/2f/9a682ffc-7b79-b965-2c83-ad9e7269238a/mzaf_5934772997073979759.plus.aac.p.m4a",
  "Frank Ocean|Pink + White":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/45/a8/a2/45a8a2e0-9516-86b2-66ea-e8b2bf71de68/mzaf_10773372944954067241.plus.aac.p.m4a",
  "Frank Ocean|Self Control":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/ba/cc/4d/bacc4dda-b762-0c0a-5ef0-6c2fad1bdb5c/mzaf_8909701195572310967.plus.aac.p.m4a",
  "J. Cole|4 Your Eyez Only":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/2e/09/43/2e0943db-3a78-f46a-286a-b3eb0c365810/mzaf_3644211831283843704.plus.aac.p.m4a",
  "J. Cole|Love Yourz":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/e1/29/3a/e1293a6f-2d84-da7b-35e3-9bb910f08a9b/mzaf_9577951752384160469.plus.aac.p.m4a",
  "J. Cole|Neighbors":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/13/5c/2c/135c2c6d-a11d-1516-a4e6-f55084e6374d/mzaf_14980915360282086844.plus.aac.p.m4a",
  "J. Cole|Ville Mentality":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/4d/db/3d/4ddb3d81-b930-afa5-a6b5-99d076c26127/mzaf_12012653443244867576.plus.aac.p.m4a",
  "J. Cole|Wet Dreamz":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/a8/3e/ed/a83eed0b-4a11-4365-35d2-662b11dec248/mzaf_7193495623824731495.plus.aac.p.m4a",
  "Kanye West|All of the Lights":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/5c/6e/05/5c6e05cf-7dfb-8ade-073a-ce283c7b6819/mzaf_12823917616239521881.plus.aac.p.m4a",
  "Kanye West|Devil in a New Dress":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f7/52/4f/f7524f7b-fad2-37a7-add1-46dc4777b1a7/mzaf_18227421752647567547.plus.aac.p.m4a",
  "Kanye West|Flashing Lights":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/c3/c6/c6/c3c6c652-2f19-1511-c8e9-e9caf9b6b4ac/mzaf_8110172512846397285.plus.aac.p.m4a",
  "Kanye West|Homecoming":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/a0/b6/ac/a0b6ac24-9509-19e7-85a7-0be507d17c02/mzaf_5643812388289006313.plus.aac.p.m4a",
  "Kanye West|I Wonder":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/03/f4/d5/03f4d5de-1c09-33eb-7852-279a71ac989f/mzaf_15614695934438135653.plus.aac.p.m4a",
  "Kanye West|Runaway":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/71/6b/1c/716b1cc9-373f-16b5-9407-ffefa257b103/mzaf_12754007498418561566.plus.aac.p.m4a",
  "Laufey|From the Start":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/b1/90/96/b190963f-8e5e-9b41-9eaa-5b0c6a6e187a/mzaf_13234981298659947368.plus.aac.p.m4a",
  "Laufey|Goddess":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/1b/25/4d/1b254d6f-f5c1-2be5-ff17-daea7d36ce61/mzaf_16854218537060326351.plus.aac.p.m4a",
  "Laufey|Promise":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/91/e1/95/91e1955e-ac99-64fc-2315-4ce8d4881589/mzaf_10067315834237608158.plus.aac.p.m4a",
  "Malcolm Todd|Earrings":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d4/97/06/d4970622-b87b-9af3-b375-21af92396852/mzaf_1443470814230920096.plus.aac.p.m4a",
  "Malcolm Todd|Roommates":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/83/28/93/832893ec-2977-b98e-3f39-5ba163df3508/mzaf_2525217399935561635.plus.aac.p.m4a",
  "Malcolm Todd|Sweet Boy":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d0/82/2e/d0822e13-ca65-5354-fdc3-752f9e436d24/mzaf_13310718639918742988.plus.aac.p.m4a",
  "Michael Jackson|Beat It":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/88/cd/46/88cd46bd-dba7-1dc2-a63b-e8c111ac4fc3/mzaf_4042555053237612653.plus.aac.p.m4a",
  "Michael Jackson|Billie Jean":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/dc/bc/8a/dcbc8a3e-4ce1-c00d-cc02-eda2212053c7/mzaf_8347559338388601510.plus.aac.p.m4a",
  "Michael Jackson|Human Nature":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/5b/f8/a1/5bf8a1ce-68a9-896b-b9de-abbba22bc65a/mzaf_2514540964270694755.plus.aac.p.m4a",
  "SZA|Broken Clocks":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/45/87/49/4587491b-9e6d-ce7d-44bd-7793559d6f55/mzaf_10905429609128681385.plus.aac.p.m4a",
  "SZA|Drew Barrymore":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/ce/37/fe/ce37fe6a-ff6d-40f2-0d07-313d7261c8a5/mzaf_18065607433519952771.plus.aac.p.m4a",
  "SZA|Love Galore":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/6e/72/41/6e72414d-5790-927f-9dff-cf5a98b04dc3/mzaf_4976105868631010962.plus.aac.p.m4a",
  "Tame Impala|Eventually":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview126/v4/09/93/7d/09937dd0-967b-b304-a485-053dfaf7d0c6/mzaf_16227325571594810181.plus.aac.p.m4a",
  "Tame Impala|Let It Happen":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/8d/60/fb/8d60fb3b-208b-70db-f712-801034be3130/mzaf_14872027621360090334.plus.aac.p.m4a",
  "Tame Impala|The Less I Know the Better":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/83/5a/2b/835a2b42-cfad-2bd0-117b-8150f6f0cb30/mzaf_733122625819472017.plus.aac.p.m4a",
  "The Weeknd|Blinding Lights":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/19/d6/60/19d660ff-e3a9-8377-15a3-ce4b28e89cac/mzaf_18422426156481158187.plus.aac.p.m4a",
  "The Weeknd|Die For You":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/50/50/1a/50501a86-bd74-e90d-8a56-68c9b5e6e7d6/mzaf_4588197682084244913.plus.aac.p.m4a",
  "The Weeknd|Take Me Back to LA":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/77/a3/5f/77a35f7f-b81e-87e0-1d98-9fe987a9da74/mzaf_2294823491095522908.plus.aac.p.m4a",
  "Tyler, the Creator|ARE WE STILL FRIENDS?":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/4a/8c/a4/4a8ca4b8-4646-7348-8141-7cc5225359a7/mzaf_15815358371251706305.plus.aac.p.m4a",
  "Tyler, the Creator|Darling, I":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/6b/31/85/6b3185a4-fbc0-4d23-a05b-4e32045106c6/mzaf_13533721942779610601.plus.aac.p.m4a",
  "Tyler, the Creator|EARFQUAKE":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/ee/0c/3b/ee0c3b5f-b137-ec61-a1ba-ace6c89444b2/mzaf_7976221766374151557.plus.aac.p.m4a",
  "Tyler, the Creator|GONE, GONE / THANK YOU":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/89/b9/44/89b94492-03f0-4391-83d9-17dbfad96f69/mzaf_13997211889884996544.plus.aac.p.m4a",
  "Tyler, the Creator|Like Him":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/f8/16/31/f81631fe-84f4-a48e-518e-4e11e99339c4/mzaf_13519420484368287837.plus.aac.p.m4a",
  "Tyler, the Creator|Take Your Mask Off":
    "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/f1/c8/bc/f1c8bc1c-d930-1b39-6baa-203ea92146d0/mzaf_306089533221124606.plus.aac.p.m4a",
};
