import type { Metadata, Viewport } from "next";
import { Analytics } from "@vercel/analytics/next";
import { Inter, Cormorant_Garamond, Press_Start_2P, Bebas_Neue } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/smooth-scroll";
import ScrollReveal from "@/components/scroll-reveal";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-inter",
  display: "swap",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

// Pixel display font for the 8-bit arcade (Video Games) page only.
const pressStart = Press_Start_2P({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-press-start",
  display: "swap",
});

// Tall, condensed display font for the "ETHANFLIX" (Films / Movies) page —
// stands in for the Netflix wordmark look.
const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
  display: "swap",
});

// Shown under the title in link previews and search results, so it leads with
// the person rather than repeating the name that sits directly above it.
const DESCRIPTION =
  "A family-driven student at the University of Arkansas's Walton Honors College of Business who dreams big and always looks to be a positive, genuine, and good person.";

export const metadata: Metadata = {
  // Makes every relative URL below (and the generated icon / OG image paths)
  // resolve absolutely — crawlers reject relative ones.
  metadataBase: new URL("https://ethanmiclat.com"),
  title: "Ethan Miclat",
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  authors: [{ name: "Ethan Miclat" }],
  creator: "Ethan Miclat",
  openGraph: {
    title: "Ethan Miclat",
    description: DESCRIPTION,
    siteName: "Ethan Miclat",
    url: "/",
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ethan Miclat",
    description: DESCRIPTION,
  },
  // The card image and the icons come from the file conventions next to this
  // file — opengraph-image.jpg, icon.svg, favicon.ico, apple-icon.png. All four
  // are generated by scripts/gen-social-assets.py (`npm run social`).
};

export const viewport: Viewport = {
  // Tints the browser chrome on mobile to match the page behind it. The site
  // server-renders dark and the theme toggle is a localStorage preference
  // rather than a media query, so this tracks the dark default.
  themeColor: "#141b22",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      suppressHydrationWarning
      className={`js ${inter.variable} ${cormorant.variable} ${pressStart.variable} ${bebas.variable}`}
    >
      <head>
        {/* Apply the saved theme before first paint so there's no flash. Runs
            synchronously during HTML parsing (see Next's "Preventing Flash
            before hydration" guide). Defaults to the server-rendered dark.

            Also take over scroll restoration: the app manages its own scroll
            (experiences reset to the top on entry; the homepage lands on the
            hobby panel via its hash). The browser's native restoration fires
            AFTER those and would reopen an experience at a stale scroll
            position — so switch it off up front. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{if("scrollRestoration" in history)history.scrollRestoration="manual";var t=localStorage.getItem("theme");if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t)}catch(e){}})()`,
          }}
        />
      </head>
      <body>
        <SmoothScroll />
        <ScrollReveal />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
